# -*- coding: utf-8 -*-
"""Copy of Data Cleaning - Milestone 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11oxWqUe6nhvimlkNjfkZB0bzKSEun-mi

### **Importing Libraries**
"""

import pandas as pd
import re
from sklearn.utils import resample

# Load Dataset
df = pd.read_csv("WELFake_Dataset.csv", engine="python", on_bad_lines="skip") # sometimes corrupted rows can make things harder

df.head()

print("Original Shape:", df.shape)

# Dropping null values

df = df.dropna()

print("After Dropping null values:", df.shape)

df.head()

"""### **Data Cleaning**"""

# Dropping unneccessary column
df = df.drop(columns=['Unnamed: 0'])

# Merging title and text into a single column
df['content'] = df['title'] + ' ' + df['text']

df = df[['content', 'label']]

import re
def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)         # remove URLs
    text = re.sub(r'#\S+', '', text)            # remove hashtags
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)    # remove special characters
    text = re.sub(r'\s+', ' ', text).strip()    # remove extra spaces
    return text

df['content'] = df['content'].apply(clean_text)

df = df[df['content'].str.strip() != '']

print(df['label'].value_counts())       # so it contains 1 corrupted value

df['label'] = pd.to_numeric(df['label'], errors='coerce')

df = df.dropna(subset=['label'])
df['label'] = df['label'].astype(int)

print(df['label'].value_counts())

"""### **Balancing Sample**"""

fake = df[df.label == 0]
real = df[df.label == 1]

min_count = min(len(fake), len(real))

fake_sample = resample(fake, replace=False, n_samples=min_count, random_state=42)
real_sample = resample(real, replace=False, n_samples=min_count, random_state=42)

balanced_df = pd.concat([fake_sample, real_sample]) # Shuffle
balanced_df = balanced_df.sample(frac=1, random_state=42) # Shuffle the entire balanced dataset

print("Final Shape:", balanced_df.shape)

balanced_df.to_csv("cleaned_news.csv", index=False)

# Cell 1: Setup
!pip install pandas scikit-learn xgboost nltk vaderSentiment shap category_encoders -q

import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from scipy.sparse import hstack
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import category_encoders as ce
import shap

nltk.download('stopwords')
nltk.download('punkt')
print("Libraries ready.")

# Cell 2: Load and Engineer Features
df = pd.read_csv('cleaned_news.csv')

# 1. Text Cleaning for TF-IDF
stop_words = set(stopwords.words('english'))
def clean_text(text):
    text = str(text).lower()
    # Remove special characters but keep basic structure for TF-IDF
    text = re.sub(r'[^\w\s]', '', text)
    words = [w for w in text.split() if w not in stop_words]
    return " ".join(words)

df['clean_content'] = df['content'].apply(clean_text)

# 2. Stylistic Features (The "Meaningful" Part)
# Fake news often uses different punctuation and emotion
def extract_features(text):
    text = str(text)
    return pd.Series({
        'text_length': len(text),
        'exclamation_count': text.count('!'),
        'question_count': text.count('?'),
        'capital_ratio': sum(1 for c in text if c.isupper()) / (len(text) + 1)
    })

stylistic_features = df['content'].apply(extract_features)

# 3. Sentiment Features (VADER)
# Fake news often has extreme (very positive or very negative) sentiment
sentiment = SentimentIntensityAnalyzer()
df['sentiment'] = df['content'].apply(lambda x: sentiment.polarity_scores(str(x))['compound'])

# Combine all numeric features
numeric_features = pd.concat([stylistic_features, df[['sentiment']]], axis=1)

print("Feature Engineering Complete.")
print(numeric_features.head())

# Cell 3: Vectorization
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
X_text = tfidf.fit_transform(df['clean_content'])

# Convert numeric features to sparse matrix to combine with TF-IDF
from scipy.sparse import csr_matrix
X_numeric = csr_matrix(numeric_features.values)

# Combine Text + Numeric Features
X_combined = hstack([X_text, X_numeric])
y = df['label']

# Split
X_train, X_test, y_train, y_test = train_test_split(X_combined, y, test_size=0.2, random_state=42)

# Train XGBoost
print("Training Model...")
model = XGBClassifier(n_estimators=300, learning_rate=0.1, max_depth=6, eval_metric='logloss', use_label_encoder=False)
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"\nFinal Accuracy: {acc:.4f}")
print(classification_report(y_test, y_pred))

# Cell 4: Explainability (SHAP)
# Create feature names list
feature_names = list(tfidf.get_feature_names_out()) + list(numeric_features.columns)

# Explain the model
explainer = shap.TreeExplainer(model)
# Use a subset of test data for speed
shap_values = explainer.shap_values(X_test[:50])

# Plot summary
shap.summary_plot(shap_values, X_test[:50].toarray(), feature_names=feature_names)